sudo: required
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem update --system
  - gem install bundler
addons:
  firefox: latest
git:
  depth: 1
branches:
  except:
    - static

# Make sure to change the script below

script:
  - bundle exec jekyll build -d _site

deploy:
  - provider: s3
    access_key_id: $AWS_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: cul-s3-dlst-travis-frontlinenurses-prod
    region: us-west-2
    skip_cleanup: true
    local_dir: _site
    on:
      branch: master
